### ISSUE TITLE
/public/home/chcg/anaconda3/envs/pangenome/bin/SynDiv_c cal 运行时间过长

### ISSUE THREAD

**Issue by cheninouc** [JiaoLab2021/SynDiv#4]
感谢您提供的软件
我运行SynDiv时卡在以下这个这一步2天了，一直在运行但是没有结果数据并且也没有报错：
`[2024-10-30 22:29:19,630] CMD: /public/home/chcg/anaconda3/envs/pangenome/bin/SynDiv_c cal -t 10 -r /public1/node3_chcg/CC_HH_ZRH1/comparative_genome_analysis/10.sydiv/genomes/refgenome.fa --coor /public1/node3_chcg/CC_HH_ZRH1/comparative_genome_analysis/10.sydiv/coor/SynDiv.coor.out --no_syn /public1/node3_chcg/CC_HH_ZRH1/comparative_genome_analysis/10.sydiv/no_syn/SynDiv.no_syn.out --syri_outs /public1/node3_chcg/CC_HH_ZRH1/comparative_genome_analysis/10.sydiv/no_syn_alignment/SynDiv.no_syn_alignment.out --buffer 1 --aligns /public1/node3_chcg/CC_HH_ZRH1/comparative_genome_analysis/10.sydiv/nucmer/black.Chr1.aligns /public1/node3_chcg/CC_HH_ZRH1/comparative_genome_analysis/10.sydiv/nucmer/ccs.Chr1.aligns /public1/node3_chcg/CC_HH_ZRH1/comparative_genome_analysis/10.sydiv/nucmer/MG.Chr1.aligns /public1/node3_chcg/CC_HH_ZRH1/comparative_genome_analysis/10.sydiv/nucmer/orange.Chr1.aligns /public1/node3_chcg/CC_HH_ZRH1/comparative_genome_analysis/10.sydiv/nucmer/vn1.Chr1.aligns -n black ccs MG orange vn1 -o /public1/node3_chcg/CC_HH_ZRH1/comparative_genome_analysis/10.sydiv/cal/SynDiv.cal.out`

我运行SynDiv按照您github上提供的脚本生成了相应的alian和syri的结果如下：
```
tree  nucmer/
nucmer
├── black.Chr10.aligns
├── black.Chr1.aligns
├── black.Chr2.aligns
├── black.Chr3.aligns
├── black.Chr4.aligns
├── black.Chr5.aligns
├── black.Chr6.aligns
├── black.Chr7.aligns
├── black.Chr8.aligns
├── black.Chr9.aligns
├── black.coords
├── black.delta
├── black.filter.delta
├── black.log
├── ccs.Chr10.aligns
├── ccs.Chr1.aligns
├── ccs.Chr2.aligns
├── ccs.Chr3.aligns
├── ccs.Chr4.aligns
├── ccs.Chr5.aligns
├── ccs.Chr6.aligns
├── ccs.Chr7.aligns
├── ccs.Chr8.aligns
├── ccs.Chr9.aligns
├── ccs.coords
├── ccs.delta
├── ccs.filter.delta
├── ccs.log
├── MG.Chr10.aligns
├── MG.Chr1.aligns
├── MG.Chr2.aligns
├── MG.Chr3.aligns
├── MG.Chr4.aligns
├── MG.Chr5.aligns
├── MG.Chr6.aligns
├── MG.Chr7.aligns
├── MG.Chr8.aligns
├── MG.Chr9.aligns
├── MG.coords
├── MG.delta
├── MG.filter.delta
├── MG.log
├── nohup.out
├── orange.Chr10.aligns
├── orange.Chr1.aligns
├── orange.Chr2.aligns
├── orange.Chr3.aligns
├── orange.Chr4.aligns
├── orange.Chr5.aligns
├── orange.Chr6.aligns
├── orange.Chr7.aligns
├── orange.Chr8.aligns
├── orange.Chr9.aligns
├── orange.coords
├── orange.delta
├── orange.filter.delta
├── orange.log
├── tmp.sh
├── vn1.Chr10.aligns
├── vn1.Chr1.aligns
├── vn1.Chr2.aligns
├── vn1.Chr3.aligns
├── vn1.Chr4.aligns
├── vn1.Chr5.aligns
├── vn1.Chr6.aligns
├── vn1.Chr7.aligns
├── vn1.Chr8.aligns
├── vn1.Chr9.aligns
├── vn1.coords
├── vn1.delta
├── vn1.filter.delta
└── vn1.log
```
```
syri/
├── black.log
├── black.syri.log
├── black.syri.out
├── black.syri.summary
├── black.syri.vcf
├── ccs.log
├── ccs.syri.log
├── ccs.syri.out
├── ccs.syri.summary
├── ccs.syri.vcf
├── MG.log
├── MG.syri.log
├── MG.syri.out
├── MG.syri.summary
├── MG.syri.vcf
├── orange.log
├── orange.syri.log
├── orange.syri.out
├── orange.syri.summary
├── orange.syri.vcf
├── vn1.log
├── vn1.syri.log
├── vn1.syri.out
├── vn1.syri.summary
└── vn1.syri.vcf

```
我首先对Chr1进行SynDiv计算：
SynDiv -r genome/refgenome.fa -c chr1_configuration.txt
```
cat SynDiv -r refgenome.fa -c configuration.txt:
black   genomes/black.fa        nucmer/black.Chr1.aligns        syri/black.syri.out
ccs     genomes/ccs.fa  nucmer/ccs.Chr1.aligns  syri/ccs.syri.out
MG      genomes/MG.fa   nucmer/MG.Chr1.aligns   syri/MG.syri.out
orange  genomes/orange.fa       nucmer/orange.Chr1.aligns       syri/orange.syri.out
vn1     genomes/vn1.fa  nucmer/vn1.Chr1.aligns  syri/vn1.syri.out
```

到目前位置程序并为出现报错，也没有结果的输出，期待您的回复

**Comment by duzezhen** [comment]
有可能是计算量过大导致的，您可以查看`SynDiv_c cal`的`PID`进程号，然后使用`less /proc/PID/fd/2`来查看该步骤的具体log输出。

如果您是在集群上运行的任务，您可能需要到运行任务的节点去查看进程和相应文件。

**Comment by cheninouc** [comment]
感谢您的回复
下面是/proc/335949/fd/2的输出内容：
```
[main::2024-10-30 22:29:19] You are using SynDiv (v1.1.2)

[main_cal::2024-10-30 22:29:19] Running ...
[main_cal::2024-10-30 22:29:19] Change Global Parameters ...
[main_cal::2024-10-30 22:29:19] debug: 0
[main_cal::2024-10-30 22:29:19] threads: 10
[main_cal::2024-10-30 22:29:19] readBuffer: 1 MB
[main_cal::2024-10-30 22:29:19] Parse Parameters ...
[main_cal::2024-10-30 22:29:19] Building Syntenic Coordinates Index ...
[main_cal::2024-10-30 22:29:21] Building Reference Genome Index ...
[build_fasta_index::2024-10-30 22:29:21] Compute the length of each chromosome in the reference genome.
[main_cal::2024-10-30 22:29:24] Calculating Syntenic Diversity ...
[calculate::2024-10-30 22:29:24] Calculate: reference
[calculate::2024-10-30 22:29:24] Calculate: MG
[calculate::2024-10-30 22:29:24] Calculate: black
[calculate::2024-10-30 22:29:24] Calculate: ccs
[calculate::2024-10-30 22:29:24] Calculate: orange
[merge::2024-10-30 22:35:58] Combine the computation results of reference.

```
加上参考基因组总共6个基因组，每个基因组的大小才0.6g

**Comment by duzezhen** [comment]
log信息看不出来具体的原因，计算只用了六分钟，但一直卡在合并这一步。程序的CPU利用率不是0%吧？

如果方便的话，可以分享您的数据让我们测试下。

```
[calculate::2024-11-04 16:19:43] Calculate: reference
[calculate::2024-11-04 16:19:43] Calculate: An-1
[calculate::2024-11-04 16:19:43] Calculate: C24
[calculate::2024-11-04 16:19:43] Calculate: Cvi
[calculate::2024-11-04 16:19:43] Calculate: Eri
[calculate::2024-11-04 16:19:43] Calculate: Kyo
[calculate::2024-11-04 16:19:43] Calculate: Ler
[merge::2024-11-04 16:21:04] Combine the computation results of reference.
[merge::2024-11-04 16:23:36] Combine the computation results of An-1.
[merge::2024-11-04 16:23:37] Combine the computation results of C24.
[merge::2024-11-04 16:23:38] Combine the computation results of Cvi.
[merge::2024-11-04 16:23:38] Combine the computation results of Eri.
[merge::2024-11-04 16:23:39] Combine the computation results of Kyo.
[merge::2024-11-04 16:23:39] Combine the computation results of Ler.
[calculate::2024-11-04 16:23:40] Results are being saved to 'test.cal.out'
[calculate::2024-11-04 16:25:44] Results (insertion) are being saved to 'test.cal.out.ins'
[main_cal::2024-11-04 16:25:44] Done ...
```

上述是拟南芥的测试数据，可以看到合并这一步还是非常快的。

**Comment by cheninouc** [comment]
感谢您及时的回复，我终于发现问题出现的原因了，我在得到分染色体的aligns文件后，后面合并不同染色体的aligns文件出现了问题，因此导致程序一直卡在这一步。
我得到了SynDiv.cal.out文件Syntenic_Diversity列范围为[0-1]，一般按照小于等于0.2的区域作为共线性区域，大于等于0.6作为非共线区域吗？

**Comment by duzezhen** [comment]
您好，我们是通过Syntenic_Diversity值的大小来描述共线性程度的，值越大，共线性程度就越低。

在群体研究中，我们定义Syntenic_Diversity（用`SynDiv_c window`按窗口和步长统计后的结果）前10%为高度非共线性区域，可以用这个来描述种群的分化程度。

您可以提供下两次合并aligns文件的代码吗？我们尝试修复下该bug

**Comment by cheninouc** [comment]
我在使用`cat ../sample.id | parallel -j 5 -k "for i in (cat ../chr.id); do cat {}."$i".aligns >> {}.aligns; done"` 合并时，显示**（**不符合bash，所以我改成了下面的方式循环读取chr.id文件
`cat ../sample.id | parallel -j 5 -k "cat ../chr.id | while read i ; do cat {}.$i.aligns >> {}.aligns; done"`

**Comment by cheninouc** [comment]
您好，我再解读cal目录下的两个输出文件是存在一个疑问：
在**SynDiv.cal.out.ins**文件中：
```
#Insertion
#CHROM  POS     Syntenic_Diversity
Chr1    431368  1
```
在**SynDiv.cal.out**文件中：
`Chr1    431368  15      10      0.333333`
这两个文件在相同位置会有两个共线性多态性的值，他们分别表示什么呢

**Comment by cheninouc** [comment]
您好，我再解读cal目录下的两个输出文件是存在一个疑问：
在**SynDiv.cal.out.ins**文件中：
```
#Insertion
#CHROM  POS     Syntenic_Diversity
Chr1    431368  1
```
在**SynDiv.cal.out**文件中：
`Chr1    431368  15      10      0.333333`
这两个文件在相同位置共线性多态性存在差异，他们分别表示什么呢

**Comment by cheninouc** [comment]
您好，在统计最后的结果的时候发现了一个问题，我研究的物种有10条染色体。当我使用包含10条染色体的genome.fa文件通过genome2SynDiv_config和SynDiv两个步程序之后得到的结果共线性多态性最大值在0.6。当我把其中某一条染色体提取出来通过genome2SynDiv_config和SynDiv两个步程序之后得到的结果共线性多态性最大值在1。我检查了这两个的cal.out文件发现他们存在明显的差别：
SynDiv.all.chr.cal.out:
```
Chr2    1       15      10      0.333333
Chr2    2       15      10      0.333333
Chr2    3       15      10      0.333333
Chr2    4       15      10      0.333333
Chr2    5       15      10      0.333333
Chr2    6       15      10      0.333333
Chr2    7       15      10      0.333333
Chr2    8       15      10      0.333333
Chr2    9       15      10      0.333333
```
SynDiv.chr.2.cal.out:
```
Chr2    1       15      1       0.933333
Chr2    2       15      1       0.933333
Chr2    3       15      1       0.933333
Chr2    4       15      1       0.933333
Chr2    5       15      1       0.933333
Chr2    6       15      1       0.933333
Chr2    7       15      1       0.933333
Chr2    8       15      1       0.933333
Chr2    9       15      1       0.933333
```
出现这个结果是否是染色体间的移位对共线性多态性产生了很大的影响

**Comment by duzezhen** [comment]
> 您好，我再解读cal目录下的两个输出文件是存在一个疑问： 在**SynDiv.cal.out.ins**文件中：
> 
> ```
> #Insertion
> #CHROM  POS     Syntenic_Diversity
> Chr1    431368  1
> ```
> 
> 在**SynDiv.cal.out**文件中： `Chr1 431368 15 10 0.333333` 这两个文件在相同位置共线性多态性存在差异，他们分别表示什么呢

`SynDiv.cal.out.ins`文件是插入序列之间的共线性多样性。因为没办法将插入序列直接转换为参考基因组的坐标，所以只能将它们的结果单独输出。

`SynDiv.cal.out`记录的是除插入外的共线性多样性，它包含参考基因组每个位点上的情况，下游分析主要参考这个结果。

如果您研究的位点，主要是通过插入引起的变化，这个时候就需要参考`SynDiv.cal.out.ins`文件的结果了。

--------------------------------
![QQ_1731051344037](https://github.com/user-attachments/assets/102e0917-407d-4692-a165-d783edb263f6)
比如上图箭头所指的三个位点，都是插入，SynDiv会计算这三条序列之间的相似度，然后输出到`SynDiv.cal.out.ins`文件。

**Comment by duzezhen** [comment]
> 您好，在统计最后的结果的时候发现了一个问题，我研究的物种有10条染色体。当我使用包含10条染色体的genome.fa文件通过genome2SynDiv_config和SynDiv两个步程序之后得到的结果共线性多态性最大值在0.6。当我把其中某一条染色体提取出来通过genome2SynDiv_config和SynDiv两个步程序之后得到的结果共线性多态性最大值在1。我检查了这两个的cal.out文件发现他们存在明显的差别： SynDiv.all.chr.cal.out:
> 
> ```
> Chr2    1       15      10      0.333333
> Chr2    2       15      10      0.333333
> Chr2    3       15      10      0.333333
> Chr2    4       15      10      0.333333
> Chr2    5       15      10      0.333333
> Chr2    6       15      10      0.333333
> Chr2    7       15      10      0.333333
> Chr2    8       15      10      0.333333
> Chr2    9       15      10      0.333333
> ```
> 
> SynDiv.chr.2.cal.out:
> 
> ```
> Chr2    1       15      1       0.933333
> Chr2    2       15      1       0.933333
> Chr2    3       15      1       0.933333
> Chr2    4       15      1       0.933333
> Chr2    5       15      1       0.933333
> Chr2    6       15      1       0.933333
> Chr2    7       15      1       0.933333
> Chr2    8       15      1       0.933333
> Chr2    9       15      1       0.933333
> ```
> 
> 出现这个结果是否是染色体间的移位对共线性多态性产生了很大的影响

按理说两种结果应该不会差距很大，这个需要检查比对结果，或者SyRI的输出才能确定原因。您可以看下整体的趋势是否一致。

我们之前两种方式的结果是差不多的，我们最近再用拟南芥的数据确认下。

**Comment by duzezhen** [comment]
我们在拟南芥上也进行了测试，单条染色体和全基因组的结果相比，确实在染色体开头会有些微小差异，但整体上差异不大，其余部分的结果基本一致。

这些差异可能是全基因组比对时部分片段比对到了其他染色体，正如您提到的，由易位引起的影响。

感谢您的反馈与使用！

**Comment by cheninouc** [comment]
感谢您耐心的回复，我想问一下共线性块之间的not aligned region是否也是不会添加到SynDiv.cal.out文件中，而是当作一种插入变异输出到SynDiv.cal.out.ins文件呢？
因此，SynDiv在计算共线性多态性是在染色体结构差异水平还是染色体差异序列水平上的呢？
由于昨天晚上有课程，错过了与您交流的机会。
![1731588063948](https://github.com/user-attachments/assets/0e322b13-f671-4c24-9183-a99dcaecb79e)

**Comment by duzezhen** [comment]
抱歉这么晚才回复您，最近有点忙！

未必对上的片段会添加到SynDiv.cal.out文件中的，SynDiv计算的共线性多样性是基于序列水平上的计算的。
