### ISSUE TITLE
How to visualize synteny between genomes using SynDiv

### ISSUE THREAD

**Issue by CSU-KangHu** [JiaoLab2021/SynDiv#5]
Hi @duzezhen,

Thank you for developing such a useful tool. I am currently interested in using [SynDiv](https://github.com/JiaoLab2021/SynDiv) to create synteny plots for multiple Arabidopsis genomes, similar to the image below. Could you please guide me on how to do this?

![image](https://github.com/user-attachments/assets/d32020c4-89a8-405f-ae14-911072c0de30)

**Comment by JiaB-He** [comment]
Thank you for your attention. The results from SynDiv are mainly used to describe the degree of population differentiation, and the image you referenced can be visualized using the [plotsr](https://github.com/schneebergerlab/plotsr) package from SyRI. Please feel free to reach out anytime for further discussion.
