### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'text'

### ISSUE THREAD

**Issue by lamevan** [JiaoLab2021/SynDiv#6]
作者您好，当我按照conda方式安装之后
发现找不到cal_syn_fst
之后又按照Linux 安装的方式安装了
在跑前面的步骤都很顺利的情况下
cal_syn_fst报了这个错：

可以麻烦您看看吗？
File "/data/home/xxx/miniconda3/envs/syndiv/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'text'
谢谢！
感谢您开发了SynDiv !

**Comment by duzezhen** [comment]
可能是您配置文件中有`text`字符，该位置需要的是数字。

不过现在的`cal_syn_fst`流程确实有点复杂，我们最近会把这个功能添加到SynDiv_c代码中，这样一条命令就可以出结果。我们之后更新好之后给您说下。

**Comment by lamevan** [comment]
> 可能是您配置文件中有`text`字符，该位置需要的是数字。
> 
> 不过现在的`cal_syn_fst`流程确实有点复杂，我们最近会把这个功能添加到SynDiv_c代码中，这样一条命令就可以出结果。我们之后更新好之后给您说下。

好的，谢谢！
祝顺利！

**Comment by duzezhen** [comment]
您好，计算`Fst`的功能已经添加到`SynDiv_c`程序中了，您更新下代码，然后使用下边的代码就可以计算。

```
SynDiv_c Fst -c subPopulation1.cal.out sunPopulation2.cal.out population.cal.out -o SynDiv.Fst.out
```
